import { Section } from "./Section";
import { SectionTitle } from "./SectionTitle";
import { Experience, WorkExperience } from "./WorkExperience";

const experiences: Experience[] = [
  {
    start: new Date("2023/02/01"),
    end: new Date("2023/10/01"),
    location: "Remote",
    company: "Scaleup Finance",
    companyLink: "https://www.scaleup.finance/",
    title: "Senior Frontend Developer",
    description:
      "During my time at Scaleup, I played a pivotal role within my team, contributing to a diverse range of complex projects. One of the aspects I particularly enjoyed was crafting a readable codebase while working on intricate financial systems, ensuring a balance between technical complexity and business requirements. This role provided an excellent platform for me to showcase my development skills effectively and my ability to break down designs and complex problems into manageable tickets for me and the team. It also highlighted my ability to figure out how each team member worked most effectively and ensure they were set up for success.",
    skills: [
      "Next.js",
      "React",
      "Typescript",
      "Turborepo",
      "Jest",
      "Tailwind",
      "React Query",
      "HTML",
      "Vercel",
      "GIT",
      "Vite",
      "ESLint",
      "Docker",
      "MongoDB",
      "REST",
      "CI/CD",
    ],
  },
  {
    start: new Date("2022/11/01"),
    end: new Date("2023/02/01"),
    location: "Remote",
    company: "Aurelia",
    title: "Full Stack Software Engineer",
    description:
      'At Aurelia, I was a full stack engineer working on building a new infrastructure for businesses. My notable contribution was the implementation of "If blocks" that allowed dynamic manipulation of elements in a tree data structure, which required an understanding of data structures and algorithms. This challenging work further honed my technical skills and ability to solve complex problems in a fast-paced, constantly evolving environment whilst ensuring performant code.',
    skills: [
      "Next.js",
      "React",
      "Typescript",
      "Jest",
      "CSS",
      "HTML",
      "SASS",
      "Node.js",
      "GIT",
      "Webpack",
      "ESLint",
      "REST",
      "CI/CD",
    ],
  },
  {
    start: new Date("2022/01/01"),
    end: new Date("2022/08/01"),
    location: "Remote",
    company: "HomeViews",
    companyLink: "https://www.homeviews.com/",
    title: "Senior Frontend Developer",
    description:
      "At HomeViews, I assumed a leadership role for the front-end team, overseeing mentorship, application architecture, and the development of processes to ensure the team delivers maximum value. I managed a direct report, regularly communicated with key stakeholders including directors and product managers, and effectively collaborated with the entire organisation.",
    skills: [
      "Next.js",
      "React",
      "Typescript",
      "Cypress",
      "HTML",
      "Styled components",
      "Storybook",
      "NX",
      "GIT",
      "Webpack",
      "ESLint",
      "REST",
      "CI/CD",
    ],
  },
  {
    start: new Date("2021/12/01"),
    end: new Date("2022/12/01"),
    location: "Remote",
    company: "Bumble",
    companyLink: "https://bumble.com/en/",
    title: "Frontend Developer",
    description:
      "I was a part of the early days team and played a key role in implementing and enhancing features for new users of the web application. I also contributed to a substantial React migration project and was one of the first developers to implement Jest tests. I really enjoyed the emphasis on accessibility at Bumble, due to having such a large user base, it meant that more care was taken for catering to everyone.",
    skills: [
      "Next.js",
      "React",
      "Typescript",
      "Jest",
      "CSS",
      "HTML",
      "Backbone.js",
      "SASS",
      "GIT",
      "Webpack",
      "ESLint",
      "Docker",
      "REST",
      "CI/CD",
    ],
  },
  {
    start: new Date("2020/04/01"),
    end: new Date("2020/12/01"),
    location: "Remote",
    company: "Eigen Technologies",
    companyLink: "https://eigentech.com/",
    title: "Software Developer",
    description:
      "At Eigen, I worked on enhancing an existing functionality while prioritising scalable performance and implementing automated testing to maintain its efficiency.",
    skills: [
      "React",
      "Typescript",
      "Jest",
      "CSS",
      "HTML",
      "Python",
      "SASS",
      "GIT",
      "Webpack",
      "ESLint",
      "Redux",
      "Docker",
      "REST",
      "CI/CD",
    ],
  },
  {
    start: new Date("2017/09/01"),
    end: new Date("2020/03/01"),
    location: "London",
    company: "Elder",
    companyLink: "https://www.elder.org/",
    title: "Frontend Developer 2",
    description:
      "I worked on a diverse range of React-based web applications and took ownership of the technical updates for the public-facing website. As the longest serving Frontend developer on the team, I served as a mentor to new and existing team members and actively participated in the requirements gathering phase of the development cycle, ensuring a good long term strategy for the codebase and team. I found a lot of value in thinking about the users and listening to user interviews, when approaching creating MVP’s.",
    skills: [
      "React",
      "Flow typing",
      "Jest",
      "Cypress",
      "CSS",
      "HTML",
      "Confluence",
      "Jekyll",
      "Docker",
      "React Intl",
      "Storybook",
      "SASS",
      "Node.js",
      "GIT",
      "Webpack",
      "Redux",
      "ESLint",
      "Docker",
      "REST",
      "CI/CD",
    ],
  },
  {
    start: new Date("2016/04/01"),
    end: new Date("2017/07/01"),
    location: "London",
    company: "MullenLowe Group",
    companyLink: "https://www.mullenloweglobal.com/",
    title: "Junior Web Developer",
    description:
      "As a Full-stack developer, I had the opportunity to create numerous custom websites, igniting my passion for Front-end development and specifically for React.",
    skills: [
      "React",
      "Javascript",
      "Grunt",
      "Gulp",
      "CSS",
      "HTML",
      "PHP",
      "jQuery",
      "SASS",
      "GIT",
      "Node.js",
      "Webpack",
      "ESLint",
      "PostgreSQL",
      "REST",
      "Wordpress"
    ],
  },
];

export const WorkSection = () => (
  <Section id="work">
    <SectionTitle>Work</SectionTitle>
    <WorkExperience experiences={experiences} />
  </Section>
);
