name: Run build
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Runs Build
        run: npm run build
      - run: echo "Status is ${{ job.status }}."
