name: Linting and Type check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Runs lint
        run: npm run lint
      - name: Runs Typecheck
        run: npm run typecheck
      - run: echo "Status is ${{ job.status }}."
